import type { GlobalThemeOverrides } from 'naive-ui'

// ── 主题色常量 ────────────────────────────────
export const ACCENT_COLORS = {
  orange: {
    primary: '#FF6B00',
    primaryHover: '#FF8C42',
    primaryPressed: '#CC5500',
    primarySuppl: '#FF8C42',
  },
  purple: {
    primary: '#7c3aed',
    primaryHover: '#8b5cf6',
    primaryPressed: '#6d28d9',
    primarySuppl: '#a78bfa',
  }
} as const

export type AccentColor = 'orange' | 'purple'

export function getAccentColors(accent: AccentColor) {
  return accent === 'purple' ? ACCENT_COLORS.purple : ACCENT_COLORS.orange
}

// ── 状态色常量 ────────────────────────────────
const STATUS = {
  success: '#18a058',
  warning: '#f0a020',
  error: '#d03050',
  info: '#2080f0',
} as const

// ── 深色主题原始值 ────────────────────────────────
const DARK = {
  bgPrimary: '#111118',
  bgSecondary: '#1a1a24',
  bgCard: '#1a1a24',
  bgModal: '#1e1e28',
  bgSidebar: 'rgba(28, 28, 32, 0.98)',
  bgMenubar: 'rgba(40, 40, 45, 0.98)',
  bgHover: 'rgba(255,255,255,0.06)',
  bgActive: 'rgba(255,255,255,0.08)',
  bgRowHover: 'rgba(255,255,255,0.03)',
  borderPrimary: 'rgba(255,255,255,0.08)',
  borderSecondary: 'rgba(255,255,255,0.06)',
  textPrimary: 'rgba(255,255,255,0.95)',
  textSecondary: 'rgba(255,255,255,0.85)',
  textTertiary: 'rgba(255,255,255,0.7)',
  textQuaternary: 'rgba(255,255,255,0.5)',
  textDisabled: 'rgba(255,255,255,0.38)',
  textHint: 'rgba(255,255,255,0.35)',
  codeBg: '#1a1a24',
  codeComment: 'rgba(255,255,255,0.35)',
}

// ── 浅色主题原始值 ────────────────────────────────
const LIGHT = {
  bgPrimary: '#ffffff',
  bgSecondary: '#ffffff',
  bgCard: '#ffffff',
  bgModal: '#ffffff',
  bgSidebar: 'rgba(248,248,252,0.99)',
  bgMenubar: 'rgba(255,255,255,0.97)',
  bgHover: 'rgba(0,0,0,0.04)',
  bgActive: 'rgba(0,0,0,0.06)',
  bgRowHover: 'rgba(0,0,0,0.02)',
  borderPrimary: 'rgba(0,0,0,0.08)',
  borderSecondary: 'rgba(0,0,0,0.07)',
  textPrimary: 'rgba(0,0,0,0.90)',
  textSecondary: 'rgba(0,0,0,0.82)',
  textTertiary: 'rgba(0,0,0,0.65)',
  textQuaternary: 'rgba(0,0,0,0.50)',
  textDisabled: 'rgba(0,0,0,0.35)',
  textHint: 'rgba(0,0,0,0.28)',
  codeBg: '#f8f8fc',
  codeComment: 'rgba(0,0,0,0.35)',
}

// ── 生成完整 CSS（深色 + 浅色覆盖） ────────────────────────────────
export function generateCSS(accent: AccentColor = 'orange'): string {
  const ac = getAccentColors(accent)

  // 数据类型色（保持一致，仅调整透明度）
  const typeStrBgL = 'rgba(77,184,255,0.10)'
  const typeNumBgL = 'rgba(255,107,0,0.10)'
  const typeBoolBgL = 'rgba(251,146,60,0.10)'
  const typeDateBgL = 'rgba(167,139,250,0.10)'
  const typeObjBgL = 'rgba(52,211,153,0.10)'
  const typeArrBgL = 'rgba(96,165,250,0.10)'
  const typeBinBgL = 'rgba(245,158,11,0.10)'

  const templateCSS = `/* Auto-generated by theme-config.ts — do not edit manually */
:root {
  /* 背景色 */
  --bg-primary: ${DARK.bgPrimary};
  --bg-secondary: ${DARK.bgSecondary};
  --bg-tertiary: rgba(30,30,35,0.95);
  --bg-elevated: rgba(40,40,45,0.98);
  --bg-sidebar: ${DARK.bgSidebar};
  --bg-menubar: ${DARK.bgMenubar};
  --bg-tabbar: rgba(0,0,0,0.25);
  --bg-hover: ${DARK.bgHover};
  --bg-active: ${DARK.bgActive};
  --bg-selected: rgba(255,255,255,0.08);
  --bg-row-hover: ${DARK.bgRowHover};
  /* 文字色 */
  --text-primary: ${DARK.textPrimary};
  --text-secondary: ${DARK.textSecondary};
  --text-tertiary: ${DARK.textTertiary};
  --text-quaternary: ${DARK.textQuaternary};
  --text-disabled: ${DARK.textDisabled};
  --text-placeholder: ${DARK.textDisabled};
  --text-hint: ${DARK.textHint};
  /* 边框色 */
  --border-primary: ${DARK.borderPrimary};
  --border-secondary: ${DARK.borderSecondary};
  --border-hover: rgba(255,255,255,0.10);
  --border-strong: rgba(255,255,255,0.12);
  /* 主题色 */
  --accent-primary: ${ac.primary};
  --accent-primary-hover: ${ac.primaryHover};
  --accent-primary-pressed: ${ac.primaryPressed};
  --accent-primary-subtle: rgba(${hexToRgb(ac.primary)},0.15);
  --accent-primary-subtle-hover: rgba(${hexToRgb(ac.primary)},0.25);
  /* 阴影 */
  --shadow-soft-sm: 0 4px 20px rgba(0,0,0,0.28);
  --shadow-soft: 0 8px 32px rgba(0,0,0,0.35);
  --shadow-rail: 4px 0 24px rgba(0,0,0,0.18);
  /* 状态色 */
  --status-error: ${STATUS.error};
  --status-warning: ${STATUS.warning};
  --status-info: ${STATUS.info};
  --status-success: ${STATUS.success};
  /* 数据类型色 */
  --type-string: #4db8ff;
  --type-string-bg: rgba(77,184,255,0.12);
  --type-number: ${ac.primary};
  --type-number-bg: rgba(${hexToRgb(ac.primary)},0.12);
  --type-boolean: #fb923c;
  --type-boolean-bg: rgba(251,146,60,0.12);
  --type-date: #a78bfa;
  --type-date-bg: rgba(167,139,250,0.12);
  --type-object: #34d399;
  --type-object-bg: rgba(52,211,153,0.12);
  --type-array: #60a5fa;
  --type-array-bg: rgba(96,165,250,0.12);
  --type-null: rgba(255,255,255,0.35);
  --type-binary: #f59e0b;
  --type-binary-bg: rgba(245,158,11,0.12);
  /* 代码编辑器 */
  --code-bg: ${DARK.codeBg};
  --code-comment: ${DARK.codeComment};
  /* 布局尺寸 */
  --sidebar-width: 260px;
  --tab-bar-height: 38px;
}

body.dark-theme {
  background: var(--bg-primary);
  color: var(--text-primary);
}

/* ── 浅色模式覆盖 ── */
body.light-theme {
  --bg-primary: ${LIGHT.bgPrimary};
  --bg-secondary: ${LIGHT.bgSecondary};
  --bg-tertiary: rgba(255,255,255,0.98);
  --bg-elevated: rgba(255,255,255,0.99);
  --bg-sidebar: ${LIGHT.bgSidebar};
  --bg-menubar: ${LIGHT.bgMenubar};
  --bg-tabbar: rgba(0,0,0,0.03);
  --bg-hover: ${LIGHT.bgHover};
  --bg-active: ${LIGHT.bgActive};
  --bg-selected: rgba(0,0,0,0.06);
  --bg-row-hover: ${LIGHT.bgRowHover};
  --text-primary: ${LIGHT.textPrimary};
  --text-secondary: ${LIGHT.textSecondary};
  --text-tertiary: ${LIGHT.textTertiary};
  --text-quaternary: ${LIGHT.textQuaternary};
  --text-disabled: ${LIGHT.textDisabled};
  --text-placeholder: ${LIGHT.textDisabled};
  --text-hint: ${LIGHT.textHint};
  --border-primary: ${LIGHT.borderPrimary};
  --border-secondary: ${LIGHT.borderSecondary};
  --border-hover: rgba(0,0,0,0.12);
  --border-strong: rgba(0,0,0,0.15);
  --accent-primary-subtle: rgba(${hexToRgb(ac.primary)},0.10);
  --accent-primary-subtle-hover: rgba(${hexToRgb(ac.primary)},0.18);
  --shadow-soft-sm: 0 4px 20px rgba(15,23,42,0.06);
  --shadow-soft: 0 10px 40px rgba(15,23,42,0.08);
  --shadow-rail: 4px 0 28px rgba(15,23,42,0.04);
  --type-string-bg: ${typeStrBgL};
  --type-number-bg: ${typeNumBgL};
  --type-boolean-bg: ${typeBoolBgL};
  --type-date-bg: ${typeDateBgL};
  --type-object-bg: ${typeObjBgL};
  --type-array-bg: ${typeArrBgL};
  --type-null: rgba(0,0,0,0.30);
  --type-binary-bg: ${typeBinBgL};
  --code-bg: ${LIGHT.codeBg};
  --code-comment: ${LIGHT.codeComment};
  background: var(--bg-primary);
  color: var(--text-primary);
}

/* ── 全局布局覆盖 ── */
body.light-theme .conn-sidebar,
body.light-theme .navigator-sider {
  background: ${LIGHT.bgSidebar} !important;
}
body.light-theme .content-layout,
body.light-theme .workspace-shell,
body.light-theme .workspace-main {
  background: var(--bg-primary) !important;
}
body.light-theme .mysql-workspace,
body.light-theme .ch-workspace,
body.light-theme .mongo-workspace,
body.light-theme .redis-workspace {
  background: var(--bg-primary) !important;
}
body.light-theme .sidebar,
body.light-theme .connection-tree {
  background: ${LIGHT.bgSidebar} !important;
}
body.light-theme .db-tree-panel {
  background: ${LIGHT.bgSidebar};
  border-right-color: ${LIGHT.borderSecondary};
}
body.light-theme .workspace-tabs {
  background: rgba(0,0,0,0.03) !important;
  border-bottom-color: ${LIGHT.borderPrimary} !important;
}
body.light-theme .tab { color: ${LIGHT.textQuaternary}; }
body.light-theme .tab:hover { color: ${LIGHT.textPrimary}; background: ${LIGHT.bgHover}; }
body.light-theme .tab.active {
  color: ${ac.primary};
  border-bottom-color: ${ac.primary};
  background: rgba(${hexToRgb(ac.primary)},0.05);
}
body.light-theme .sql-textarea,
body.light-theme .q-textarea,
body.light-theme .value-textarea {
  background: #fff !important;
  color: #1a1a1a !important;
}
body.light-theme .app-side-nav {
  background: #fafbfc !important;
  border-right-color: rgba(15,23,42,0.06);
}
body.light-theme .tab-bar {
  background: rgba(0,0,0,0.03) !important;
  border-bottom-color: ${LIGHT.borderPrimary} !important;
}
body.light-theme .tab-btn {
  color: ${LIGHT.textQuaternary} !important;
}
body.light-theme .tab-btn:hover {
  color: ${LIGHT.textPrimary} !important;
  background: ${LIGHT.bgHover} !important;
}
body.light-theme .mysql-workspace .tab-btn.active,
body.light-theme .ch-workspace .tab-btn.active {
  color: ${ac.primary} !important;
  border-bottom-color: ${ac.primary} !important;
}
body.light-theme .table-browse .browse-toolbar,
body.light-theme .table-schema .schema-toolbar,
body.light-theme .table-indexes .idx-toolbar,
body.light-theme .sql-editor-wrap .sql-toolbar {
  border-bottom-color: ${LIGHT.borderSecondary};
}
body.light-theme .table-browse .browse-pagination {
  border-top-color: ${LIGHT.borderSecondary};
}
body.light-theme .mysql-workspace .def-val {
  color: ${LIGHT.textQuaternary};
  background: ${LIGHT.bgHover};
}
body.light-theme .mysql-workspace .null-val { color: ${LIGHT.textDisabled}; }
body.light-theme .mysql-workspace .id-val { color: #d97706; }
body.light-theme .mysql-workspace .type-sm {
  color: ${LIGHT.textQuaternary};
  background: ${LIGHT.bgActive};
}
body.light-theme .mysql-explorer .sec-label { color: ${LIGHT.textTertiary}; }
body.light-theme .mysql-explorer .badge {
  color: ${LIGHT.textDisabled};
  background: ${LIGHT.bgActive};
}
body.light-theme .mysql-explorer .item-row:hover {
  background: rgba(77,184,255,0.08);
}
body.light-theme .mysql-explorer .item-row.active {
  background: rgba(77,184,255,0.15);
}
body.light-theme .mysql-explorer .item-meta { color: ${LIGHT.textDisabled}; }
body.light-theme .mysql-explorer .loading-hint { color: ${LIGHT.textDisabled}; }
body.light-theme .mysql-explorer .empty { color: ${LIGHT.textDisabled}; }
body.light-theme .ch-workspace .tab-btn.active {
  color: #fb923c !important;
  border-bottom-color: #fb923c !important;
}
body.light-theme .ch-explorer .sec-label { color: ${LIGHT.textTertiary}; }
body.light-theme .ch-explorer .badge {
  color: ${LIGHT.textDisabled};
  background: ${LIGHT.bgActive};
}
body.light-theme .ch-explorer .item-row:hover {
  background: rgba(251,146,60,0.08);
}
body.light-theme .ch-explorer .item-row.active {
  background: rgba(251,146,60,0.15);
}
body.light-theme .ch-explorer .item-meta { color: ${LIGHT.textDisabled}; }
body.light-theme .mongo-workspace .tab-btn.active {
  color: #60a5fa !important;
  border-bottom-color: #60a5fa !important;
}
body.light-theme .mongo-explorer .sec-label { color: ${LIGHT.textTertiary}; }
body.light-theme .mongo-explorer .badge {
  color: ${LIGHT.textDisabled};
  background: ${LIGHT.bgActive};
}
body.light-theme .mongo-explorer .item-row:hover {
  background: rgba(96,165,250,0.08);
}
body.light-theme .mongo-explorer .item-row.active {
  background: rgba(96,165,250,0.15);
}
body.light-theme .mongo-explorer .item-meta { color: ${LIGHT.textDisabled}; }
body.light-theme .connection-tree .tree-title { color: ${LIGHT.textHint}; }
body.light-theme .connection-tree .connection-name { color: ${LIGHT.textPrimary}; }
body.light-theme .connection-tree .connection-type { color: ${LIGHT.textDisabled}; }
body.light-theme .settings-container {
  background: var(--bg-primary);
  color: var(--text-primary);
}
body.light-theme .settings-container .settings-sidebar {
  background: ${LIGHT.bgSecondary};
  border-right-color: ${LIGHT.borderSecondary};
}
body.light-theme .settings-container .nav-item {
  color: ${LIGHT.textTertiary};
}
body.light-theme .settings-container .nav-item:hover {
  background: ${LIGHT.bgHover};
}
body.light-theme .settings-container .nav-item.is-active {
  background: rgba(${hexToRgb(ac.primary)},0.10);
  color: ${ac.primary};
}
body.light-theme .settings-container .setting-item {
  background: ${LIGHT.bgRowHover};
  border-color: ${LIGHT.borderSecondary};
}
body.light-theme .settings-container .setting-label { color: ${LIGHT.textPrimary}; }
body.light-theme .settings-container .setting-desc { color: ${LIGHT.textDisabled}; }
body.light-theme .settings-container .driver-card {
  background: ${LIGHT.bgRowHover};
  border-color: ${LIGHT.borderSecondary};
}
body.light-theme .settings-container .driver-name { color: ${LIGHT.textPrimary}; }
body.light-theme .settings-container .driver-version { color: ${LIGHT.textDisabled}; }
body.light-theme .logs-panel .log-list { background: transparent; }
body.light-theme .logs-panel .log-entry {
  background: ${LIGHT.bgRowHover};
}
body.light-theme .logs-panel .log-entry:hover { background: ${LIGHT.bgHover}; }
body.light-theme .logs-panel .log-ts { color: ${LIGHT.textDisabled}; }
body.light-theme .logs-panel .log-src { color: ${LIGHT.textHint}; }
body.light-theme .logs-panel .log-msg { color: ${LIGHT.textSecondary}; }
body.light-theme .about-card {
  background: ${LIGHT.bgSecondary};
  border-color: ${LIGHT.borderPrimary};
}
body.light-theme .about-body .about-name { color: ${LIGHT.textPrimary}; }
body.light-theme .about-body .about-tagline { color: ${LIGHT.textDisabled}; }
body.light-theme .about-body .about-meta-grid .meta-item { background: ${LIGHT.bgRowHover}; }
body.light-theme .about-body .about-meta-grid .meta-label { color: ${LIGHT.textHint}; }
body.light-theme .about-body .about-meta-grid .meta-value { color: ${LIGHT.textSecondary}; }
body.light-theme .about-body .about-copyright { color: ${LIGHT.textDisabled}; }

/* ── 深色模式全局布局覆盖 ── */
body.dark-theme .conn-sidebar,
body.dark-theme .navigator-sider {
  background: var(--bg-sidebar) !important;
}
body.dark-theme .content-layout,
body.dark-theme .workspace-shell,
body.dark-theme .workspace-main {
  background: var(--bg-primary) !important;
}
body.dark-theme .mysql-workspace,
body.dark-theme .ch-workspace,
body.dark-theme .mongo-workspace,
body.dark-theme .redis-workspace {
  background: var(--bg-primary) !important;
}
body.dark-theme .sidebar,
body.dark-theme .connection-tree {
  background: var(--bg-sidebar) !important;
}
body.dark-theme .db-tree-panel {
  background: var(--bg-sidebar);
}
body.dark-theme .workspace-tabs {
  background: rgba(0,0,0,0.20);
  border-bottom: 1px solid var(--border-secondary);
}
body.dark-theme .tab { color: var(--text-tertiary); }
body.dark-theme .tab:hover { color: var(--text-primary); background: var(--bg-row-hover); }
body.dark-theme .tab.active {
  color: var(--accent-primary);
  border-bottom-color: var(--accent-primary);
  background: var(--accent-primary-subtle);
}
body.dark-theme .app-side-nav {
  background: var(--bg-menubar);
  border-right-color: var(--border-secondary);
}
body.dark-theme .tab-bar {
  background: var(--bg-tabbar);
  border-bottom: 1px solid var(--border-secondary);
}
body.dark-theme .tab-btn { color: var(--text-quaternary); }
body.dark-theme .tab-btn:hover { color: var(--text-secondary); }
body.dark-theme .mysql-workspace .tab-btn.active {
  color: var(--type-string);
  border-bottom-color: var(--type-string);
}
body.dark-theme .ch-workspace .tab-btn.active {
  color: var(--type-boolean);
  border-bottom-color: var(--type-boolean);
}
body.dark-theme .mongo-workspace .tab-btn.active {
  color: var(--type-array);
  border-bottom-color: var(--type-array);
}
body.dark-theme .redis-workspace {
  background: var(--bg-primary);
}
body.dark-theme .settings-container {
  background: var(--bg-primary);
}
body.dark-theme .settings-container .settings-sidebar {
  background: var(--bg-secondary);
  border-right-color: var(--border-secondary);
}
body.dark-theme .logs-panel .log-list { background: transparent; }
body.dark-theme .logs-panel .log-entry { background: var(--bg-row-hover); }
body.dark-theme .logs-panel .log-entry:hover { background: var(--bg-hover); }
body.dark-theme .about-card {
  background: var(--bg-secondary);
  border-color: var(--border-primary);
}
body.dark-theme .about-body .about-name { color: var(--text-primary); }
body.dark-theme .about-body .about-meta-grid .meta-item { background: var(--bg-row-hover); }
body.dark-theme .about-body .about-meta-grid .meta-label { color: var(--text-hint); }
body.dark-theme .about-body .about-meta-grid .meta-value { color: var(--text-secondary); }
body.dark-theme .about-body .about-copyright { color: var(--type-null); }
`

  // Utility: convert #RRGGBB to R, G, B
  function hexToRgb(hex: string): string {
    const r = parseInt(hex.slice(1, 3), 16)
    const g = parseInt(hex.slice(3, 5), 16)
    const b = parseInt(hex.slice(5, 7), 16)
    return `${r},${g},${b}`
  }

  const rgb = hexToRgb(ac.primary)
  return templateCSS
    .replace(/\$\{hexToRgb\(ac\.primary\)\}/g, rgb)
}

// Helper used outside generateCSS
function hexToRgb(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16)
  const g = parseInt(hex.slice(3, 5), 16)
  const b = parseInt(hex.slice(5, 7), 16)
  return `${r},${g},${b}`
}

// ── Naive UI 主题覆盖 ────────────────────────────────
export function createThemeOverrides(
  isDark: boolean,
  accent: AccentColor = 'orange'
): GlobalThemeOverrides {
  const bg = isDark ? DARK : LIGHT
  const ac = getAccentColors(accent)
  const accentSubtle = `rgba(${hexToRgb(ac.primary)},${isDark ? '0.15' : '0.10'})`

  return {
    common: {
      primaryColor: ac.primary,
      primaryColorHover: ac.primaryHover,
      primaryColorPressed: ac.primaryPressed,
      primaryColorSuppl: ac.primarySuppl,
      bodyColor: bg.bgPrimary,
      borderRadius: '12px',
      borderRadiusSmall: '8px',
      fontSize: '14px',
      fontSizeMini: '12px',
      fontSizeSmall: '13px',
      fontSizeMedium: '14px',
      fontSizeLarge: '15px',
      fontSizeHuge: '16px',
      heightMini: '24px',
      heightSmall: '28px',
      heightMedium: '34px',
      heightLarge: '40px',
      heightHuge: '46px',
      // Status colors
      successColor: STATUS.success,
      warningColor: STATUS.warning,
      errorColor: STATUS.error,
      infoColor: STATUS.info
    },
    Button: {
      colorPrimary: ac.primary,
      colorHoverPrimary: ac.primaryHover,
      colorPressedPrimary: ac.primaryPressed,
      colorFocusPrimary: ac.primary,
      borderPrimary: `1px solid ${ac.primary}`,
      borderHoverPrimary: `1px solid ${ac.primaryHover}`,
      borderPressedPrimary: `1px solid ${ac.primaryPressed}`,
      borderFocusPrimary: `1px solid ${ac.primary}`,
      textColorPrimary: '#ffffff',
      textColorHoverPrimary: '#ffffff',
      textColorPressedPrimary: '#ffffff',
      textColorFocusPrimary: '#ffffff',
      textColor: bg.textSecondary,
      textColorHover: bg.textPrimary,
      textColorPressed: bg.textPrimary,
      color: isDark ? 'rgba(255,255,255,0.08)' : '#ffffff',
      colorHover: isDark ? 'rgba(255,255,255,0.12)' : '#f0f0f0',
      colorPressed: isDark ? 'rgba(255,255,255,0.16)' : '#e6e6e6',
      border: isDark ? '1px solid rgba(255,255,255,0.12)' : '1px solid #d9d9d9',
      borderHover: isDark ? '1px solid rgba(255,255,255,0.20)' : '1px solid #bfbfbf',
      borderPressed: isDark ? '1px solid rgba(255,255,255,0.24)' : '1px solid #a8a8a8',
      borderFocus: isDark ? '1px solid rgba(255,255,255,0.24)' : `1px solid ${ac.primary}`,
      borderRadiusMedium: '8px',
      borderRadiusSmall: '6px',
      borderRadiusLarge: '10px',
      paddingLarge: '0 20px',
      paddingMedium: '0 16px',
      paddingSmall: '0 12px'
    },
    Card: {
      color: bg.bgCard,
      colorModal: bg.bgModal,
      borderRadius: '18px',
      borderColor: bg.borderSecondary,
      borderColorModal: bg.borderPrimary
    },
    Input: {
      color: isDark ? 'rgba(255,255,255,0.03)' : '#ffffff',
      colorFocus: isDark ? 'rgba(255,255,255,0.05)' : '#ffffff',
      borderColor: isDark ? 'rgba(255,255,255,0.10)' : '#d9d9d9',
      borderColorFocus: ac.primary,
      borderRadius: '8px',
      heightMedium: '34px',
      colorDisabled: isDark ? 'rgba(255,255,255,0.02)' : '#f5f5f5',
      textColor: bg.textPrimary,
      caretColor: ac.primary
    },
    Select: {
      peers: {
        InternalSelection: {
          color: isDark ? 'rgba(255,255,255,0.03)' : '#ffffff',
          borderFocus: `1px solid ${ac.primary}`,
          borderRadius: '8px',
          heightMedium: '34px',
          textColor: bg.textPrimary
        }
      }
    },
    Tree: {
      color: 'transparent',
      nodeTextColor: bg.textSecondary,
      nodeTextColorHover: bg.textPrimary,
      nodeColorHover: bg.bgHover,
      arrowColor: bg.textDisabled
    },
    Menu: {
      itemTextColor: bg.textTertiary,
      itemTextColorHover: bg.textPrimary,
      itemTextColorActive: ac.primary,
      itemColorHover: bg.bgHover,
      itemColorActive: accentSubtle,
      borderColor: bg.borderSecondary
    },
    Tabs: {
      tabTextColorLine: bg.textTertiary,
      tabTextColorActiveLine: ac.primary,
      tabTextColorHoverLine: bg.textPrimary,
      tabColorSegment: bg.bgRowHover,
      tabBorderColor: bg.borderPrimary,
      colorActive: ac.primary,
      barColor: ac.primary
    },
    Tag: {
      borderRadius: '6px',
      heightMedium: '28px',
      heightSmall: '22px'
    },
    Dialog: {
      color: bg.bgModal,
      borderRadius: '18px',
      titleTextColor: bg.textPrimary
    },
    Message: {
      colorSuccess: isDark ? `rgba(24,160,88,0.20)` : `rgba(24,160,88,0.10)`,
      textColorSuccess: isDark ? '#36b374' : STATUS.success,
      colorError: isDark ? `rgba(208,48,80,0.20)` : `rgba(208,48,80,0.10)`,
      textColorError: isDark ? '#e04060' : STATUS.error,
      colorWarning: isDark ? `rgba(240,160,32,0.22)` : `rgba(240,160,32,0.12)`,
      textColorWarning: isDark ? '#f5b942' : STATUS.warning,
      colorInfo: isDark ? `rgba(32,128,240,0.20)` : `rgba(32,128,240,0.10)`,
      textColorInfo: isDark ? '#4090f8' : STATUS.info
    },
    DataTable: {
      thColor: isDark ? bg.bgRowHover : '#f5f6f8',
      thColorHover: bg.bgHover,
      tdColor: bg.bgPrimary,
      tdColorHover: bg.bgRowHover,
      tdColorStriped: isDark ? 'rgba(255,255,255,0.02)' : 'rgba(0,0,0,0.02)',
      borderColor: bg.borderSecondary,
      thTextColor: bg.textTertiary,
      tdTextColor: bg.textSecondary
    },
    Dropdown: {
      color: bg.bgModal,
      optionColorHover: bg.bgHover,
      optionTextColor: bg.textSecondary,
      borderRadius: '8px'
    },
    Tooltip: {
      color: DARK.bgModal,
      textColor: DARK.textPrimary,
      borderRadius: '6px'
    },
    Layout: {
      color: bg.bgPrimary,
      siderColor: bg.bgSidebar,
      headerColor: bg.bgPrimary,
      footerColor: bg.bgPrimary
    },
    Scrollbar: {
      color: isDark ? 'rgba(255,255,255,0.15)' : 'rgba(0,0,0,0.15)',
      colorHover: isDark ? 'rgba(255,255,255,0.25)' : 'rgba(0,0,0,0.25)'
    }
  }
}
